"""
ml/build_threshold_sweep.py — Regenerate ml/sweep_cache.json from the REAL
trained models (ml/models/*.joblib) scored on the REAL PaySim test split.

Why this file exists
---------------------
The old ml/sweep_cache.json was produced by ml/evaluate.py against
ml/eval_set.csv — a synthetic, trivially-separable evaluation set generated by
ml/build_eval_set.py (fraud == channel_risk_score == 0.94, a hardcoded rule).
That produced a threshold sweep with ~100% precision/recall and 0 FP/FN at
almost every threshold from 0.01-0.99, which is exactly the "suspiciously
perfect metric" CLAUDE.md bans, and directly contradicted the honest numbers
in ml/metrics_report.md (produced by ml/train.py on the real PaySim test
split).

This script closes that gap: it reuses the EXACT SAME feature engineering and
time-aware train/test split as ml/train.py (by importing time_aware_split
from it), loads the models ml/train.py already saved to ml/models/, and
sweeps decision thresholds 0-100 against the real held-out test set. No
retraining is required — this only re-scores the existing models — so this is
fast to re-run any time transactions.csv or the saved models change.

Usage
-----
    python ml/build_threshold_sweep.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix, precision_score, recall_score

ROOT = Path(__file__).parent.parent
DATA_PATH = ROOT / "data" / "processed" / "transactions.csv"
MODELS_DIR = ROOT / "ml" / "models"
SWEEP_PATH = ROOT / "ml" / "sweep_cache.json"

sys.path.insert(0, str(ROOT))
from ml.features import FEATURE_COLS_BASELINE, FEATURE_COLS_FUSION, TARGET_COL, engineer_features
from ml.train import time_aware_split  # same split fn used to produce metrics_report.md

# Same cost assumptions as the Analytics dashboard's default sliders
# (web/src/pages/AnalyticsPage.jsx fnCost/fpCost state).
FN_COST = 250_000.0
FP_COST = 400.0


def generate_sweep(y_true: np.ndarray, y_prob: np.ndarray) -> list[dict]:
    pts = []
    for t_int in range(101):
        threshold = t_int / 100.0
        y_pred = (y_prob >= threshold).astype(int)
        cm = confusion_matrix(y_true, y_pred, labels=[0, 1])
        tn, fp, fn, tp = cm.ravel()

        prec = float(precision_score(y_true, y_pred, zero_division=0))
        rec = float(recall_score(y_true, y_pred, zero_division=0))
        total_cost = (fn * FN_COST) + (fp * FP_COST)

        pts.append(
            {
                "threshold_int": t_int,
                "threshold": threshold,
                "precision": prec,
                "recall": rec,
                "FP": int(fp),
                "FN": int(fn),
                "total_cost": float(total_cost),
            }
        )
    return pts


def main():
    metadata_path = MODELS_DIR / "metadata.json"
    if not metadata_path.exists():
        raise FileNotFoundError(
            f"{metadata_path} not found — run `python ml/train.py` first so there "
            "are real models to score."
        )
    metadata = json.loads(metadata_path.read_text())
    best_base_name = metadata["best_baseline_model"]
    best_fusion_name = metadata["best_fusion_model"]
    if not best_fusion_name:
        raise RuntimeError(
            "metadata.json has no best_fusion_model — was ml/train.py run with "
            "--baseline-only? The threshold sweep needs both baseline and fusion "
            "models."
        )

    print(f"[load] Reading {DATA_PATH} …")
    df = pd.read_csv(DATA_PATH)
    print(f"[load] {len(df):,} rows, fraud_rate={df[TARGET_COL].mean():.4%}")

    print("[features] Engineering features …")
    df_fe = engineer_features(df)

    # Identical split to ml/train.py -> identical test set to metrics_report.md
    _, test_df = time_aware_split(df_fe, test_frac=0.15)

    y_test = test_df[TARGET_COL].values
    X_test_base = test_df[FEATURE_COLS_BASELINE]
    X_test_fusion = test_df[FEATURE_COLS_FUSION]

    print(f"[load] Loading models {best_base_name}.joblib / {best_fusion_name}.joblib …")
    base_model = joblib.load(MODELS_DIR / f"{best_base_name}.joblib")
    fusion_model = joblib.load(MODELS_DIR / f"{best_fusion_name}.joblib")

    print("[score] Scoring transaction-only baseline …")
    y_prob_base = base_model.predict_proba(X_test_base)[:, 1]

    print("[score] Scoring full fusion model …")
    y_prob_fusion = fusion_model.predict_proba(X_test_fusion)[:, 1]

    print("[score] Scoring cyber-only modality (raw cyber_flag as score) …")
    y_prob_cyber = test_df["cyber_flag"].astype(float).values

    print("[sweep] Computing threshold sweeps (0-100) on the real held-out test set …")
    sweep_results = {
        "transaction_only": generate_sweep(y_test, y_prob_base),
        "cyber_only": generate_sweep(y_test, y_prob_cyber),
        "full_fusion": generate_sweep(y_test, y_prob_fusion),
    }

    with open(SWEEP_PATH, "w") as f:
        json.dump(sweep_results, f)

    n_pos = int(y_test.sum())
    n_neg = int(len(y_test) - n_pos)
    print(f"[sweep] Test set: {len(y_test):,} rows ({n_pos:,} fraud / {n_neg:,} legit)")
    mid = sweep_results["full_fusion"][50]
    print(
        f"[sweep] full_fusion @ threshold=0.50 -> precision={mid['precision']:.4f} "
        f"recall={mid['recall']:.4f} FP={mid['FP']} FN={mid['FN']}"
    )
    print(f"[sweep] Cached to {SWEEP_PATH}")


if __name__ == "__main__":
    main()
