import os
import json
import datetime
import pandas as pd
from pathlib import Path
from sklearn.metrics import average_precision_score, precision_score, recall_score, f1_score, confusion_matrix
from ml.predict import tabular_score

def evaluate():
    eval_csv = Path(__file__).parent / "eval_set.csv"
    if not eval_csv.exists():
        raise FileNotFoundError(f"Evaluation set not found at {eval_csv}")
    
    print(f"Loading evaluation set from {eval_csv}...")
    df = pd.read_csv(eval_csv)
    y_true = df["is_fraud"].values
    
    # Defaults for cost model
    FN_COST = 250000
    FP_COST = 400
    n_total = len(y_true)
    
    print("Scoring transaction-only baseline...")
    y_prob_txn = tabular_score(df, use_fusion=False)
    
    print("Scoring cyber-only modality...")
    # Cyber flag maps directly to probabilities (1 for compromise, 0 for safe)
    y_prob_cyber = df["cyber_compromise_in_window"].astype(float).values
    
    print("Scoring full fusion model...")
    y_prob_fusion = tabular_score(df, use_fusion=True)
    
    def get_metrics(y_prob, threshold=0.5):
        y_pred = (y_prob >= threshold).astype(int)
        cm = confusion_matrix(y_true, y_pred, labels=[0, 1])
        tn, fp, fn, tp = cm.ravel()
            
        total_cost = (fn * FN_COST) + (fp * FP_COST)
        cost_per_million = (total_cost / n_total) * 1_000_000
        
        return {
            "pr_auc": float(average_precision_score(y_true, y_prob)),
            "precision": float(precision_score(y_true, y_pred, zero_division=0)),
            "recall": float(recall_score(y_true, y_pred, zero_division=0)),
            "f1": float(f1_score(y_true, y_pred, zero_division=0)),
            "confusion_matrix": {
                "TP": int(tp),
                "FP": int(fp),
                "TN": int(tn),
                "FN": int(fn)
            },
            "total_cost": float(total_cost),
            "cost_per_million": float(cost_per_million)
        }

    print("Computing baseline metrics...")
    metrics_txn = get_metrics(y_prob_txn)
    metrics_cyber = get_metrics(y_prob_cyber)
    metrics_fusion = get_metrics(y_prob_fusion)
    
    best_single_pr_auc = max(metrics_txn["pr_auc"], metrics_cyber["pr_auc"])
    delta_pr_auc = metrics_fusion["pr_auc"] - best_single_pr_auc
    
    results = {
        "transaction_only": metrics_txn,
        "cyber_only": metrics_cyber,
        "full_fusion": metrics_fusion,
        "delta": {
            "fusion_vs_best_single_modality_pr_auc": delta_pr_auc
        }
    }
    
    report_path = Path(__file__).parent / "metrics_report.md"
    print(f"Writing report to {report_path}...")
    with open(report_path, "w") as f:
        f.write("# ML Evaluation Metrics Report\n\n")
        f.write("This file is automatically generated by `ml/evaluate.py`.\n\n")
        f.write("```json\n")
        f.write(json.dumps(results, indent=2))
        f.write("\n```\n")

    print("Computing threshold sweeps (0-100)...")
    sweep_results = {
        "transaction_only": [],
        "cyber_only": [],
        "full_fusion": []
    }
    
    def generate_sweep(y_prob):
        pts = []
        for t_int in range(101):
            threshold = t_int / 100.0
            y_pred = (y_prob >= threshold).astype(int)
            cm = confusion_matrix(y_true, y_pred, labels=[0, 1])
            tn, fp, fn, tp = cm.ravel()
            
            prec = float(precision_score(y_true, y_pred, zero_division=0))
            rec = float(recall_score(y_true, y_pred, zero_division=0))
            total_cost = (fn * FN_COST) + (fp * FP_COST)
            
            pts.append({
                "threshold_int": t_int,
                "threshold": threshold,
                "precision": prec,
                "recall": rec,
                "FP": int(fp),
                "FN": int(fn),
                "total_cost": float(total_cost)
            })
        return pts
    
    sweep_results["transaction_only"] = generate_sweep(y_prob_txn)
    sweep_results["cyber_only"] = generate_sweep(y_prob_cyber)
    sweep_results["full_fusion"] = generate_sweep(y_prob_fusion)
    
    sweep_path = Path(__file__).parent / "sweep_cache.json"
    with open(sweep_path, "w") as f:
        json.dump(sweep_results, f)
        
    print(f"Sweep results cached to {sweep_path}")
    print("Done.")

if __name__ == "__main__":
    evaluate()
