-- ─────────────────────────────────────────────────────────────────────────────
-- Migration: 202607260004_mobile_auth_and_pairing.sql
-- Fuzen AI — Mobile APK Authentication, QR Pairing & Password Reset Tables
-- Apply via: supabase db push  OR  supabase migration up
-- ─────────────────────────────────────────────────────────────────────────────

create extension if not exists pgcrypto;

-- ── Helper: auto-update updated_at ───────────────────────────────────────────
create or replace function public.set_updated_at()
returns trigger language plpgsql security definer as $$
begin new.updated_at = timezone('utc', now()); return new; end;
$$;

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. QR PAIRING SESSIONS
--    Generated by Developer Portal when a user clicks "Generate Pairing QR".
--    The APK scans this, calls /api/sdk/pair, and the token is consumed.
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.qr_pairing_sessions (
    id                  uuid        primary key default gen_random_uuid(),
    pair_id             text        not null unique,                -- embedded in QR payload
    bootstrap_token     text        not null unique,               -- one-time bearer token for pairing
    tenant_id           text        not null default 'TENANT_FUZEN_001',
    app_id              text        not null default 'com.fusionbank.mobileapp',
    backend_url         text        not null,                      -- https://… URL given to APK
    ws_url              text        not null,                      -- wss://… URL given to APK
    created_by_user_id  uuid        references auth.users(id) on delete set null,
    device_uuid         text,                                      -- filled in after APK completes pairing
    paired_at           timestamptz,
    status              text        not null default 'PENDING'
                            check (status in ('PENDING','CONSUMED','EXPIRED','REVOKED')),
    expires_at          timestamptz not null default (timezone('utc', now()) + interval '15 minutes'),
    created_at          timestamptz not null default timezone('utc', now()),
    updated_at          timestamptz not null default timezone('utc', now())
);

create index if not exists idx_qr_pairing_pair_id      on public.qr_pairing_sessions (pair_id);
create index if not exists idx_qr_pairing_bootstrap    on public.qr_pairing_sessions (bootstrap_token);
create index if not exists idx_qr_pairing_status       on public.qr_pairing_sessions (status);
create index if not exists idx_qr_pairing_expires_at   on public.qr_pairing_sessions (expires_at);

create trigger qr_pairing_sessions_updated_at
    before update on public.qr_pairing_sessions
    for each row execute function public.set_updated_at();

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. PASSWORD RESET TOKENS
--    Generated when a user submits "Forgot password?" with their email.
--    Link format: https://app.fuzenai.com/reset-password?token=<token>
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.password_reset_tokens (
    id              uuid        primary key default gen_random_uuid(),
    customer_id     uuid        not null references public.customers(id) on delete cascade,
    token           text        not null unique default encode(gen_random_bytes(32), 'hex'),
    email           text        not null,
    ip_address      inet,
    user_agent      text,
    used_at         timestamptz,
    status          text        not null default 'PENDING'
                        check (status in ('PENDING','USED','EXPIRED','REVOKED')),
    expires_at      timestamptz not null default (timezone('utc', now()) + interval '15 minutes'),
    created_at      timestamptz not null default timezone('utc', now()),
    updated_at      timestamptz not null default timezone('utc', now())
);

create index if not exists idx_password_reset_token      on public.password_reset_tokens (token);
create index if not exists idx_password_reset_customer   on public.password_reset_tokens (customer_id);
create index if not exists idx_password_reset_email      on public.password_reset_tokens (email);
create index if not exists idx_password_reset_expires_at on public.password_reset_tokens (expires_at);

create trigger password_reset_tokens_updated_at
    before update on public.password_reset_tokens
    for each row execute function public.set_updated_at();

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. EMAIL VERIFICATION TOKENS
--    Sent after registration. Customer must verify before full access is granted.
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.email_verification_tokens (
    id              uuid        primary key default gen_random_uuid(),
    customer_id     uuid        not null references public.customers(id) on delete cascade,
    token           text        not null unique default encode(gen_random_bytes(32), 'hex'),
    email           text        not null,
    verified_at     timestamptz,
    status          text        not null default 'PENDING'
                        check (status in ('PENDING','VERIFIED','EXPIRED','REVOKED')),
    expires_at      timestamptz not null default (timezone('utc', now()) + interval '24 hours'),
    created_at      timestamptz not null default timezone('utc', now()),
    updated_at      timestamptz not null default timezone('utc', now())
);

create index if not exists idx_email_verify_token      on public.email_verification_tokens (token);
create index if not exists idx_email_verify_customer   on public.email_verification_tokens (customer_id);
create index if not exists idx_email_verify_status     on public.email_verification_tokens (status);

create trigger email_verification_tokens_updated_at
    before update on public.email_verification_tokens
    for each row execute function public.set_updated_at();

-- ─────────────────────────────────────────────────────────────────────────────
-- 4. MOBILE APP SESSIONS
--    Tracks each authenticated mobile session (separate from SDK sessions).
--    Used for: push notifications, multi-device detection, revocation.
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.mobile_app_sessions (
    id                  uuid        primary key default gen_random_uuid(),
    customer_id         uuid        not null references public.customers(id) on delete cascade,
    device_uuid         text        not null,
    session_token       text        not null unique default encode(gen_random_bytes(48), 'base64'),
    refresh_token       text        not null unique default encode(gen_random_bytes(48), 'base64'),
    app_version         text        not null default '1.0.0',
    sdk_version         text        not null default 'FAT-SDK v2.4.1',
    push_token          text,                                      -- FCM / APNs token for alerts
    ip_address          inet,
    device_model        text,
    android_version     text,
    vpn_detected        boolean     not null default false,
    risk_score          numeric(5,2) not null default 0.0 check (risk_score between 0 and 100),
    status              text        not null default 'ACTIVE'
                            check (status in ('ACTIVE','REVOKED','EXPIRED')),
    last_active_at      timestamptz not null default timezone('utc', now()),
    expires_at          timestamptz not null default (timezone('utc', now()) + interval '30 days'),
    refresh_expires_at  timestamptz not null default (timezone('utc', now()) + interval '90 days'),
    created_at          timestamptz not null default timezone('utc', now()),
    updated_at          timestamptz not null default timezone('utc', now())
);

create index if not exists idx_mobile_sessions_customer    on public.mobile_app_sessions (customer_id);
create index if not exists idx_mobile_sessions_token       on public.mobile_app_sessions (session_token);
create index if not exists idx_mobile_sessions_refresh     on public.mobile_app_sessions (refresh_token);
create index if not exists idx_mobile_sessions_device      on public.mobile_app_sessions (device_uuid);
create index if not exists idx_mobile_sessions_status      on public.mobile_app_sessions (status);

create trigger mobile_app_sessions_updated_at
    before update on public.mobile_app_sessions
    for each row execute function public.set_updated_at();

-- ─────────────────────────────────────────────────────────────────────────────
-- 5. DEVICE PAIRING REGISTRY
--    Authoritative record of which devices are paired to which tenants/accounts.
--    The APK calls /api/sdk/pair which writes here upon successful pairing.
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.device_pairing_registry (
    id                  uuid        primary key default gen_random_uuid(),
    device_uuid         text        not null unique,
    customer_id         uuid        references public.customers(id) on delete set null,
    tenant_id           text        not null default 'TENANT_FUZEN_001',
    app_id              text        not null default 'com.fusionbank.mobileapp',
    pair_id             text        references public.qr_pairing_sessions(pair_id) on delete set null,
    device_fingerprint  text        not null,
    model               text        not null default 'unknown',
    manufacturer        text        not null default 'unknown',
    android_version     text        not null default 'unknown',
    sdk_version         text        not null default '1.0.0',
    app_version         text        not null default '1.0.0',
    access_token        text,                                      -- current bearer token for this device
    refresh_token       text,
    access_expires_at   bigint,
    refresh_expires_at  bigint,
    is_active           boolean     not null default true,
    root_detected       boolean     not null default false,
    emulator_detected   boolean     not null default false,
    trust_score         numeric(5,2) not null default 75.0 check (trust_score between 0 and 100),
    first_paired_at     timestamptz not null default timezone('utc', now()),
    last_seen_at        timestamptz not null default timezone('utc', now()),
    created_at          timestamptz not null default timezone('utc', now()),
    updated_at          timestamptz not null default timezone('utc', now())
);

create index if not exists idx_device_pairing_uuid          on public.device_pairing_registry (device_uuid);
create index if not exists idx_device_pairing_customer      on public.device_pairing_registry (customer_id);
create index if not exists idx_device_pairing_tenant        on public.device_pairing_registry (tenant_id);
create index if not exists idx_device_pairing_pair_id       on public.device_pairing_registry (pair_id);

create trigger device_pairing_registry_updated_at
    before update on public.device_pairing_registry
    for each row execute function public.set_updated_at();

-- ─────────────────────────────────────────────────────────────────────────────
-- 6. AUTH AUDIT LOG
--    Immutable log of all authentication events (login, logout, register,
--    password reset, pairing) for CERT-In compliance.
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.auth_audit_log (
    id              uuid        primary key default gen_random_uuid(),
    customer_id     uuid        references public.customers(id) on delete set null,
    device_uuid     text,
    event_type      text        not null
                        check (event_type in (
                            'REGISTER','EMAIL_VERIFY','LOGIN_SUCCESS','LOGIN_FAILED',
                            'LOGIN_CHALLENGED','LOGIN_BLOCKED','LOGOUT',
                            'PASSWORD_RESET_REQUEST','PASSWORD_RESET_SUCCESS',
                            'DEVICE_PAIRED','DEVICE_REVOKED',
                            'SESSION_REVOKED','TOKEN_REFRESHED'
                        )),
    ip_address      inet,
    user_agent      text,
    vpn_detected    boolean     default false,
    risk_score      numeric(5,2) default 0.0,
    metadata        jsonb       default '{}',
    timestamp       timestamptz not null default timezone('utc', now()),
    created_at      timestamptz not null default timezone('utc', now())
);

create index if not exists idx_auth_audit_customer   on public.auth_audit_log (customer_id);
create index if not exists idx_auth_audit_event      on public.auth_audit_log (event_type);
create index if not exists idx_auth_audit_timestamp  on public.auth_audit_log (timestamp);
create index if not exists idx_auth_audit_ip         on public.auth_audit_log (ip_address);

-- ─────────────────────────────────────────────────────────────────────────────
-- 7. PUSH NOTIFICATION REGISTRY
--    Stores FCM tokens per device for sending fraud/security alerts to the APK.
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.push_notification_registry (
    id              uuid        primary key default gen_random_uuid(),
    customer_id     uuid        not null references public.customers(id) on delete cascade,
    device_uuid     text        not null,
    push_token      text        not null,                          -- FCM Registration Token
    platform        text        not null default 'ANDROID'
                        check (platform in ('ANDROID','IOS','WEB')),
    is_active       boolean     not null default true,
    last_updated_at timestamptz not null default timezone('utc', now()),
    created_at      timestamptz not null default timezone('utc', now()),
    unique (device_uuid, push_token)
);

create index if not exists idx_push_customer    on public.push_notification_registry (customer_id);
create index if not exists idx_push_device      on public.push_notification_registry (device_uuid);
create index if not exists idx_push_active      on public.push_notification_registry (is_active);

-- ─────────────────────────────────────────────────────────────────────────────
-- ROW LEVEL SECURITY
-- ─────────────────────────────────────────────────────────────────────────────
alter table public.qr_pairing_sessions          enable row level security;
alter table public.password_reset_tokens        enable row level security;
alter table public.email_verification_tokens    enable row level security;
alter table public.mobile_app_sessions          enable row level security;
alter table public.device_pairing_registry      enable row level security;
alter table public.auth_audit_log               enable row level security;
alter table public.push_notification_registry   enable row level security;

-- Customers can read their own sessions, devices, notifications
create policy mobile_sessions_self_read on public.mobile_app_sessions
    for select using (
        customer_id in (select id from public.customers where auth_user_id = auth.uid())
    );

create policy device_pairing_self_read on public.device_pairing_registry
    for select using (
        customer_id in (select id from public.customers where auth_user_id = auth.uid())
    );

create policy auth_audit_self_read on public.auth_audit_log
    for select using (
        customer_id in (select id from public.customers where auth_user_id = auth.uid())
    );

create policy push_registry_self_read on public.push_notification_registry
    for select using (
        customer_id in (select id from public.customers where auth_user_id = auth.uid())
    );

-- Service role (backend) can do everything — controlled by ANON key restrictions
-- All writes come through FastAPI which runs as service_role

-- ─────────────────────────────────────────────────────────────────────────────
-- HELPER FUNCTIONS
-- ─────────────────────────────────────────────────────────────────────────────

-- Generate the QR JSON payload the Developer Portal encodes into a QR image
create or replace function public.generate_pairing_qr_payload(
    p_backend_url   text,
    p_ws_url        text,
    p_tenant_id     text default 'TENANT_FUZEN_001',
    p_created_by    uuid default null
)
returns jsonb
language plpgsql security definer as $$
declare
    v_pair_id           text := 'PAIR_' || upper(encode(gen_random_bytes(8), 'hex'));
    v_bootstrap_token   text := encode(gen_random_bytes(32), 'hex');
    v_expires_at        timestamptz := timezone('utc', now()) + interval '15 minutes';
begin
    insert into public.qr_pairing_sessions (
        pair_id, bootstrap_token, tenant_id,
        backend_url, ws_url,
        created_by_user_id, expires_at
    ) values (
        v_pair_id, v_bootstrap_token, p_tenant_id,
        p_backend_url, p_ws_url,
        p_created_by, v_expires_at
    );

    return jsonb_build_object(
        'backend',          p_backend_url,
        'ws',               p_ws_url,
        'pairId',           v_pair_id,
        'bootstrapToken',   v_bootstrap_token,
        'tenantId',         p_tenant_id,
        'expires',          v_expires_at
    );
end;
$$;

-- Cleanup expired tokens — call periodically via pg_cron or backend cron job
create or replace function public.cleanup_expired_auth_tokens()
returns integer
language plpgsql security definer as $$
declare
    v_count integer := 0;
begin
    -- Expire QR pairing sessions
    update public.qr_pairing_sessions
       set status = 'EXPIRED', updated_at = timezone('utc', now())
     where status = 'PENDING' and expires_at < timezone('utc', now());
    get diagnostics v_count = row_count;

    -- Expire password reset tokens
    update public.password_reset_tokens
       set status = 'EXPIRED', updated_at = timezone('utc', now())
     where status = 'PENDING' and expires_at < timezone('utc', now());

    -- Expire email verification tokens
    update public.email_verification_tokens
       set status = 'EXPIRED', updated_at = timezone('utc', now())
     where status = 'PENDING' and expires_at < timezone('utc', now());

    -- Revoke expired mobile app sessions
    update public.mobile_app_sessions
       set status = 'EXPIRED', updated_at = timezone('utc', now())
     where status = 'ACTIVE' and expires_at < timezone('utc', now());

    return v_count;
end;
$$;

-- ─────────────────────────────────────────────────────────────────────────────
-- DEMO / SEED DATA
-- Insert a demo QR pairing session for the Developer Portal default demo
-- ─────────────────────────────────────────────────────────────────────────────
insert into public.qr_pairing_sessions (
    pair_id,
    bootstrap_token,
    tenant_id,
    app_id,
    backend_url,
    ws_url,
    status,
    expires_at
) values (
    'PAIR_DEMO_DEV_001',
    'demo_bootstrap_token_dev_only',
    'TENANT_FUZEN_001',
    'com.fusionbank.mobileapp',
    'http://10.0.2.2:8001/',
    'ws://10.0.2.2:8001/ws/stream',
    'PENDING',
    timezone('utc', now()) + interval '30 days'  -- long-lived for demo
) on conflict (pair_id) do nothing;
